### ISSUE TITLE
Is there a map between workflow input labels and the location urls?

### ISSUE THREAD

**Issue by cat-bro** [galaxyproject/training-material#1891]
My use case is that I’m trying to implement some baseline workflow testing for the GTN workflows on Galaxy Australia.  I have been importing the workflows with bioblend and I’d like to invoke these every week or so to make sure that the workflows are loading and the jobs reach ‘ok’ status.  When it comes to defining the inputs, I cannot always make a logical link between the input labels and the entries in the data-library.  I think it would be awesome to have something like

```
workflow-inputs:
- rna-seq-viz-with-heatmap2:
  - label: normalized_counts:
    location: https://zenodo.org/record/2528905/files/limma-voom_normalised_counts
  - label: heatmap_genes:
    location: https://zenodo.org/record/2528905/files/heatmap_genes
```

defined somewhere (possibly tutorial `metadata.yaml`?).  I can find some of these defined in https://github.com/usegalaxy-eu/workflow-testing. There may be other resources that I have not found.  Happy to work on implementing a solution if it seems appropriate.
