### ISSUE TITLE
Incorrect example in contributing material

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/training-material#3653]
Hi,
I just noticed that the provided example to write workflow test is not correct:
https://github.com/galaxyproject/training-material/blob/f81a63225e9e1033f07e47f94bb49a83b9c046a9/topics/contributing/tutorials/create-new-tutorial-technical/tutorial.md?plain=1#L89-L92

If you use pyyaml to read this yaml you get:
```
[{'doc': 'Test sample data for the workflow', 'job': {'an_input_file': {'class': 'File', 'location': 'https://....', 'filetype': 'fasta'}}, 'outputs': {'ffn': {'asserts': {'has_text': {'text': '>B'}}}}}]
```
So the first assert test (`>A`) is not tested.

I am trying to find how to do multiple `has_text` assert. I will post here my findings.

**Comment by lldelisle** [comment]
I think the correct way is:
```
          asserts:
            - that: "has_text"
              text: ">A"
            - that: "has_text"
              text: ">B"
```
I would prefer someone specialist from the tool tests confirm but it looks like it works
