### ISSUE TITLE
502 Bad Gateway nginx/1.18.0 (Ubuntu) after Configure Galaxy to use Apptainer

### ISSUE THREAD

**Issue by j34ni** [galaxyproject/training-material#4524]
At this step https://training.galaxyproject.org/training-material/topics/admin/tutorials/apptainer/tutorial.html after having installed apptainer (version: 0.0.1) with Ansible and I checked it worked (running the hello_world example); so far so good

Then I made the changes indicated in the tutorial to group_vars/galaxyservers.yml, templates/galaxy/config/dependency_resolvers_conf.xml, templates/galaxy/config/container_resolvers_conf.yml.j2 and group_vars/galaxyservers.yml, to Configure Galaxy to use Apptainer

There was no error when I ran the playbook, but after that the Galaxy instance is not accessible any more

502 Bad Gateway
nginx/1.18.0 (Ubuntu)

I cannot see any obvious difference between the files I have and the [reference files](https://github.com/hexylena/git-gat/tree/step-6), and running the playbook with these reference files instead gives the same error

By the way, I set `galaxy_manage_cleanup: false` in group_vars/galaxyservers.yml until issue [#4519](https://github.com/galaxyproject/training-material/issues/4519) has been resolved to be able to move to the next steps

**Comment by j34ni** [comment]
@hexylena Any idea what breaks it?

**Comment by j34ni** [comment]
As far as I can tell it is these changes that make it fail:

![image](https://github.com/galaxyproject/training-material/assets/44261743/98c483f2-4376-4d69-8d3a-555f33e39182)

**Comment by bernt-matthias** [comment]
I would guess that the configuration for `container_resolvers` is wrong. It should be a list where each entry defines a `type` 
like `cached_explicit_singularity`

```
  container_resolvers:
  - type: cached_explicit_singularity
  ....
```

Your error message indicates that it tries to find a container resolver of type `container_resolvers`. 

Can you post the content of   `container_resolvers_config_file` and `container_resolvers` in your `galaxy.yml`? If `container_resolvers_config_file` is set, then please also the content of the file.

**Comment by j34ni** [comment]
@bernt-matthias Thanks for looking into this issue
I followed the tutorial (https://training.galaxyproject.org/training-material/topics/admin/tutorials/apptainer/tutorial.html) and hence this is what the file contains:

![Screenshot from 2023-11-20 09-51-31](https://github.com/galaxyproject/training-material/assets/44261743/128d4516-fe6d-4fa8-af5d-06c3c896b5ec)

**Comment by bernt-matthias** [comment]
I guess the `container_resolvers_conf.yml.j2` should be:

```
- type: cached_explicit_singularity
  cache_directory: "{{ galaxy_mutable_data_dir }}/cache/singularity/explicit/"
- type: cached_mulled_singularity
  cache_directory: "{{ galaxy_mutable_data_dir }}/cache/singularity/mulled/"
- type: mulled_singularity
  auto_install: False
  cache_directory: "{{ galaxy_mutable_data_dir }}/cache/singularity/mulled/"
- type: build_mulled_singularity
  auto_install: False
  cache_directory: "{{ galaxy_mutable_data_dir }}/cache/singularity/built/"
```

instead of 

```
container_resolvers:
  - type: cached_explicit_singularity
    cache_directory: "{{ galaxy_mutable_data_dir }}/cache/singularity/explicit/"
  - type: cached_mulled_singularity
    cache_directory: "{{ galaxy_mutable_data_dir }}/cache/singularity/mulled/"
  - type: mulled_singularity
    auto_install: False
    cache_directory: "{{ galaxy_mutable_data_dir }}/cache/singularity/mulled/"
  - type: build_mulled_singularity
    auto_install: False
    cache_directory: "{{ galaxy_mutable_data_dir }}/cache/singularity/built/"
```
