### ISSUE TITLE
Icon fallback for accessibility

### ISSUE THREAD

**Issue by erasche** [galaxyproject/training-material#933]
If the CSS fails to load (network issues, or you're using a browser which doesn't support CSS, or you have CSS blocked by default) then the training material shows blank list.

![auswahl_134](https://user-images.githubusercontent.com/458683/42684915-ccaf7fb6-8691-11e8-8fdb-4d0aee10cb36.png)

Normally the solution would be "well, have working CSS", but I think there might be an accessibility problem. Because we specify ` aria-hidden="true"` on our icons, screen readers will not read the icon. Usually a good thing, but here there is no fallback, so screen readers will only read the things I can see in my screenshot above.

I've looked for some solutions to this but haven't found anything working yet. And I need to install a screen reader to test.

**Comment by willdurand** [comment]
You could probably edit the the plugin to add "visually hidden" content, like the icon id: https://github.com/galaxyproject/training-material/blob/b990fb178e4cea274c623c1112d975441bb15ffa/_plugins/jekyll-icon-tag.rb#L20-L23

Visually hidden means the CSS will hide it, but if CSS fails to load, then it will be displayed.

**Comment by willdurand** [comment]
Using something like this in the CSS:

```css
.visually-hidden {
  border: 0;
  clip: rect(0 0 0 0);
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  width: 1px;
}
```
